version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "8443:8443"
    volumes:
      - ./cert.pem:/etc/nginx/certs/cert.pem
      - ./key.pem:/etc/nginx/certs/key.pem
      - ./myapp.conf:/etc/nginx/conf.d/myapp.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8443
